---
- hosts: all
  tasks:
      - name: "Drop all traffic from [partition_b] machines to [partition_a]"
        iptables: chain=INPUT source={{ hostvars[item].ansible_default_ipv4.address }} jump=DROP state=absent
        when: "'partition_b' in group_names"
        with_items: groups['partition_a']
